network:
  ethernets:
    eno1:
      mtu: 9000
  version: 2
  vlans:
    eno1.2:
      id: 2
      link: eno1
      mtu: 9000
    eno1.3:
      id: 3
      link: eno1
      mtu: 9000
    eno1.4:
      id: 4
      link: eno1
      mtu: 9000
    eno1.5:
      id: 5
      link: eno1
      mtu: 9000
  bridges:
    br2:
      mtu: 9000
      interfaces: [eno1.2]
      dhcp4: false
      link-local: []
      parameters:
        stp: false
        forward-delay: 0
    br3:
      mtu: 9000
      interfaces: [eno1.3]
      dhcp4: false
      link-local: []
      parameters:
        stp: false
        forward-delay: 0
    br4:
      mtu: 9000
      interfaces: [eno1.4]
      dhcp4: false
      link-local: []
      parameters:
        stp: false
        forward-delay: 0
    br5:
      mtu: 9000
      interfaces: [eno1.5]
      dhcp4: false
      link-local: []
      parameters:
        stp: false
        forward-delay: 0
    br6:
      mtu: 9000
      addresses:
      - 10.6.10.2/16
      routes:
      - to: default
        via: 10.6.0.1
      nameservers:
        addresses:
        - 10.6.0.53
        search:
        - foxden.network
      interfaces: [eno1]
      parameters:
        stp: false
        forward-delay: 0
